export const SETTINGS_CODES = {
  SETTINGS_GOT: 'SETTINGS_GOT',
  SETTINGS_SETTED: 'SETTINGS_SETTED',
  SETTINGS_REMOVED: 'SETTINGS_REMOVED',

  INVALID_KEYS: 'INVALID_KEYS',
  REMOVE_FAILED: 'REMOVE_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;
