version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto-trade-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secure_password_123
      POSTGRES_DB: crypto_trade_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: