export const BINANCE_HTTP_CLIENT = Symbol('BINANCE_HTTP_CLIENT');

export const BINANCE_CODES = {
  BINANCE_INVALID_CREDENTIALS: 'BINANCE_INVALID_CREDENTIALS',
  BINANCE_UNREACHABLE: 'BINANCE_UNREACHABLE',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;
