export const BINANCE_HTTP_CLIENT = 'BINANCE_HTTP_CLIENT';

export const BINANCE_CODES = {
  BINANCE_INVALID_CREDENTIALS: 'BINANCE_INVALID_CREDENTIALS',
  BINANCE_UNREACHEABLE: 'BINANCE_UNREACHEABLE',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;
